image: gcc

stages:
  - build

before_script:
    - apt update
    - apt -y install autoconf automake libtool libglib2.0-dev libgudev-1.0-dev libgettextpo-dev autopoint xsltproc dbus

build-no-qmi:
  stage: build
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - make install
    - popd
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/tmp/build-no-qmi --disable-gtk-doc --without-qmi
    - make
    - make check
    - make install

build-no-mbim:
  stage: build
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libqmi.git
    - pushd libqmi
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --disable-mbim-qmux
    - make
    - make install
    - popd
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/tmp/build-no-mbim --disable-gtk-doc --without-mbim
    - make
    - make check
    - make install

build-no-qmi-no-mbim:
  stage: build
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/tmp/build-no-qmi-no-mbim --disable-gtk-doc --without-qmi --without-mbim
    - make
    - make check
    - make install

build-default:
  stage: build
  script:
    - apt -y install autopoint gettext gtk-doc-tools gobject-introspection libgirepository1.0-dev libsystemd-dev libpolkit-gobject-1-dev libglib2.0-doc valac
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - make install
    - popd
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libqmi.git
    - pushd libqmi
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --enable-mbim-qmux
    - make
    - make install
    - popd
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --enable-gtk-doc --with-polkit=strict --with-suspend-resume=systemd --with-systemdsystemunitdir=/lib/systemd/system
    - make
    - make check
    - make install
    - make distcheck
